### ISSUE TITLE
Error with x!help x!help

### ISSUE THREAD

**Issue by Red5Gaming** [Xenon-Bot/xenon-main#19]
I know, its a stupid command that probably nobody will ever do again, but to help keep the bot alive and not brake it, i just put this here so the creator knows.
If you do x!help x!help, it sends a error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/xenon_worker/commands/bot.py", line 40, in process_commands
    await cmd.execute(ctx, parts)
  File "/usr/local/lib/python3.7/site-packages/xenon_worker/commands/command.py", line 288, in execute
    return await res
  File "/usr/src/app/modules/backups.py", line 225, in list
    await menu.start()
  File "/usr/local/lib/python3.7/site-packages/xenon_worker/commands/utils.py", line 86, in start
    await self.update()
  File "/usr/local/lib/python3.7/site-packages/xenon_worker/commands/utils.py", line 19, in update
    await self.update()
  File "/usr/local/lib/python3.7/site-packages/xenon_worker/commands/utils.py", line 26, in update
    await self.ctx.client.edit_message(self.msg, embed=self.make_embed(items))
  File "/usr/local/lib/python3.7/site-packages/xenon_worker/connection/mixins.py", line 119, in edit_message
    result = await self.http.edit_message(message.channel_id, message.id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/xenon_worker/connection/httpd.py", line 267, in request
    raise NotFound(r, data)
xenon_worker.connection.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
```

**Comment by ThatLifeofGames** [comment]
I can't reproduce that, and looking at the error it's probably an unrelated issue like you deleted a message it needed to interact with (for example you might have deleted a "creating backup" message)
